// WARNING: This file has automatically been generated on Tue, 06 Jul 2021 19:41:13 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package faiss

/*
#cgo LDFLAGS: -Wl,--unresolved-symbols=ignore-in-object-files
#include "faiss_c.h"
#include "Index_c.h"
#include "AutoTune_c.h"
#include "clone_index_c.h"
#include "Clustering_c.h"
#include "error_c.h"
#include "index_factory_c.h"
#include "IndexFlat_c.h"
#include "index_io_c.h"
#include "IndexIVF_c.h"
#include "IndexIVFFlat_c.h"
#include "IndexLSH_c.h"
#include "IndexPreTransform_c.h"
#include "IndexShards_c.h"
#include "MetaIndexes_c.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// FAISS_IO_FLAG_MMAP as defined in gofaiss/index_io_c.h:34
	FAISS_IO_FLAG_MMAP = 1
	// FAISS_IO_FLAG_READ_ONLY as defined in gofaiss/index_io_c.h:35
	FAISS_IO_FLAG_READ_ONLY = 2
)

// __codecvt_result as declared in bits/libio.h:180
type __codecvt_result int32

// __codecvt_result enumeration from bits/libio.h:180
const ()
