// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs /home/e00380/Documents/github/go-faiss/faiss/types.go

package faiss

type _idx int32

type _component float32

type _distance float32

type FaissRangeSearchResult struct{}

type FaissIDSelector struct{}

type FaissIndex struct{}

type FaissParameterRange struct{}

type FaissParameterSpace struct{}

type FaissClusteringParameters struct {
	Niter			int32
	Nredo			int32
	Verbose			int32
	Spherical		int32
	Update_index		int32
	Frozen_centroids	int32
	Min_points_per_centroid	int32
	Max_points_per_centroid	int32
	Seed			int32
	ref9c9731c3		*struct {
		Niter			int32
		Nredo			int32
		Verbose			int32
		Spherical		int32
		Update_index		int32
		Frozen_centroids	int32
		Min_points_per_centroid	int32
		Max_points_per_centroid	int32
		Seed			int32
	}
	allocs9c9731c3	interface{}
}

type FaissClustering struct{}

type FaissClusteringIterationStats struct{}

type FaissIndexFlat struct{}

type FaissIndexFlatIP struct{}

type FaissIndexFlatL2 struct{}

type FaissIndexFlatL2BaseShift struct{}

type FaissIndexRefineFlat struct{}

type FaissIndexFlat1D struct{}

type FaissIndexIVF struct{}

type FaissIndexIVFStats struct {
	Nq		uint32
	Nlist		uint32
	Ndis		uint32
	refda0d0668	*struct {
		Nq	uint64
		Nlist	uint64
		Ndis	uint64
	}
	allocsda0d0668	interface{}
}

type FaissIndexIVFFlat struct{}

type FaissIndexLSH struct{}

type FaissIndexPreTransform struct{}

type FaissIndexShards struct{}

type FaissIndexIDMap struct{}

type FaissIndexIDMap2 struct{}
